on:
  schedule:
  # Every day after globe_history has been uploaded
  - cron: '* */12 * * *'
  # But also on push
  push:
    branches:
    - main


jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull Calendar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget -O sports.ics 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRSHv8hgaDlBLG_bgq2Q6bm-Qk3dCVZAlq0nfPzYpTTq3MrJLsv0N9jmLOJZ5YWhjkwcG8chbVE3Et_/pub?gid=1961290111&single=true&output=tsv&range=F1:F'
        # Now we try adding them, if they have changed
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github@boring.party"
        git add RELEASES.md PREFERRED_RELEASES.txt README.md
        # Have we actually changed anything?
        if ! git diff-index --quiet HEAD --; then
          # We have changed something, so we commit and push
          git commit -m "Update RELEASES.md and PREFERRED_RELEASES.txt"
          git push
        fi
